### ISSUE TITLE
link to cocovila wiki?

### ISSUE THREAD

**Issue by dragazhar** [CoCoViLa/cocovila.github.io#16]
We have wiki for cocovila project https://github.com/CoCoViLa/CoCoViLa/wiki . Do we need link to it from home page?

**Comment by MastaP** [comment]
> Do we need link to it from home page?

yes

**Comment by dragazhar** [comment]
Where is a good place for it?

**Comment by MastaP** [comment]
Between 'Development' and 'Get...' in top menu? 
I.e. 'Development' 'Wiki' 'Get...'
or
Link in Development page near 'GitHub' btn

**Comment by dragazhar** [comment]
I choose second option

**Comment by MastaP** [comment]
ok
