### ISSUE TITLE
Links to GitHub only under "Development zone". 

### ISSUE THREAD

**Issue by dragazhar** [CoCoViLa/cocovila.github.io#23]
Users don't want to see links to github (too complex):
- [ ] links to Github are allowed only in Development zone
- [x] remove links to sourceforge (if we already migrated to github)
- [x] 'Get CoCoViLa' button must return ready zip for downloading COCOVILA without showing github
- [ ] there must be stable version ready for downloading, all other experiments and betas must be under development zone
- [ ] webstart must be simple and without command line magic #2 
- [ ] webstart manual for different platforms #3
- [x] In 'packages'. The source codes must be available as downloadable zip skipping the github stage (basically, on github there is button dowload zip for example https://github.com/CoCoViLa/HVACmodel/archive/master.zip)

**Comment by MastaP** [comment]
I think there must be links to github from package descriptions, but may be just need to rename the button from GitHub to Source Code (or just Source)
