### ISSUE TITLE
Web start manual

### ISSUE THREAD

**Issue by dragazhar** [CoCoViLa/cocovila.github.io#3]
Web start manual (opens in modal window). If web start will work
- [x] fix web start #2 
- [ ] "big button" for webstart, no command line (security certificate required)
- [x] nice manual about web start

**Comment by MastaP** [comment]
what is modal window?

**Comment by dragazhar** [comment]
Web start button opens new window , small manual must be there to describe web start process

**Comment by dragazhar** [comment]
Currently it works as is, from command line,  for future development we need to buy certificate

**Comment by vkotkas** [comment]
The current realisation of web start is not what we would like it to be. I think it is better to remove it from the homepage. Plus the explanation "Open Java settings and in Security tab add ..." is pretty ambigous. There is no "Java settings" on my machines for example.
